version: '3'
services:

  db: 
    container_name: db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE= ${MYSQL_DATABASE}
      - MYSQL_USER= ${MYSQL_USER}
      - MYSQL_PASSWORD= ${MYSQL_PASSWORD}
    volumes:
      - "./database/:/docker-entrypoint-initdb.d" 
    ports:
        - "${MYSQL_PORT}:3306"

  www:
    container_name: www
    image: php:apache
    volumes:
      - "./app:/var/www/html" 
    ports:
      - 81:80
      - 443:443 
    depends_on:
      - db
      - phpmyadmin

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST= ${PMA_HOST}
      #- PMA_PORT= ${PMA_PORT}
      - MYSQL_USER= ${PMA_USER}
      - MYSQL_PASSWORD= ${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD= ${PMA_ROOT_PASSWORD}
    depends_on:
      - db
      
  mkdocs:
    container_name: mkdocs
    image: polinux/mkdocs:1.5.2
    restart: always
    ports:
      - "8002:8000"
    environment:
      LIVE_RELOAD_SUPPORT: 'true'
      ADD_MODULES: 'fontawesome-markdown mkdocs-git-revision-date-localized-plugin mkdocs-material'
      FAST_MODE: 'true'
      DOCS_DIRECTORY: '/mkdoc'
    volumes:
      - "./mkdoc:/mkdoc"